#! /usr/bin/env sh

rm -r ~/.vscode/extensions/c-star
rm -r ~/.vscode/extensions/bnf
cp -r ./misc/c-star ~/.vscode/extensions/
cp -r ./misc/bnf    ~/.vscode/extensions/
cp ./misc/seti/seti.woff               ~/.vscode/extensions/theme-seti/icons/
cp ./misc/seti/vs-seti-icon-theme.json ~/.vscode/extensions/theme-seti/icons/