<operation6> ::= <operation6> <operator6> <operation5> | <operation5>
<operation5> ::= <operation5> <operator5> <operation4> | <operation4>
<operation4> ::= <operation4> <operator4> <operation3> | <operation3>
<operation3> ::= <operation3> <operator3> <operation2> | <operation2>
<operation2> ::= <operation2> <operator2> <operation1> | <operation1>
<operation1> ::= <operation1> <operator1> <operation0> | <operation0>
<operation0> ::= <operator0> <value> | <value>
<value>      ::= <raw: variable> | <raw: integer> | <raw: decimal> | <raw: string> | <function> | <parent>
<function>   ::= <raw: variable> "(" [ <operation6> { "," <operation6> } ] ")"
<parent>     ::= "(" <operation6> ")"
<operator0>  ::= "~" | "-" | "!"
<operator1>  ::= "^" | "&" | "|"
<operator2>  ::= "*" | "/" | "%"
<operator3>  ::= "+" | "-"
<operator4>  ::= "==" | "!=" | "<=" | "<" | ">=" | ">"
<operator5>  ::= "&&"
<operator6>  ::= "||"