;; include ("parsing/bnf/preprocessor.bnf")
#;; include ("parsing/bnf/types.bnf")

<program1> ::= "if" <operation6> [ <raw: newline> ] <operation6> [ [ <raw: newline> ] "else" <operation6> ]

#<statement> ::= <expression>