#;; include (parsing/bnf/numbers.bnf)

<operation> ::= <constant> <operator> <constant> 
<operation> ::= <operation> <operator> <constant>
<operator>  ::= "+" | "-"
<constant>  ::= "a", {"b"}, [ <spec> ]
<spec>      ::= "c"