<forward: expression>

<type> ::= [ "const" ] ( "var" | "void" | <integer-type>   | 
                                          <decimal-type>   | 
                                          <character-type> | 
                                          <string-type>    | 
                                          <boolean-type>   |
                                          <file-type>      |
                                          <pair-type>      |
                                          <raw: new-type> ) [ <dimension> ]
<integer-type> ::= ([ "unsigned" ] ( "byte" | "short" | "int" | "long" )) | "integer"
<decimal-type> ::= "half" | "float" | "double" | "decimal"
<boolean-type> ::= "bool"
<character-type> ::= "char" | "utf16" | "utf32"
<string-type> ::= "string" | "string16" | "string32"
<file-type> ::= "file" | "dir"
<pair-type> ::= "pair" [ <pair-dimension> ]
<dimension> ::= ( "*" | "&" | <array-type> | <list-type> | <dict-type>) [ <dimension> ]
<list-type> ::= "(" [ <expression> ] ")"
<array-type> ::= "[" [ <expression> ] { "," <expression> } "]"
<dict-type> ::= "{" [ <expression> ] "}"
<pair-dimension> ::= "[" <type> ":" <type> "]"