<type> ::= ( <integer> | <floating-point> | <character> | <string> ) { "*" }
<integer> ::= <signed-integer> | <unsigned-integer>
<signed-integer> ::= <integer-type>
<unsigned-integer> ::= "unsigned" <integer-type>
<integer-type> ::= "byte" | "short" | "int" | "long" | "num"
<floating-point> ::= "mini" | "float" | "double" | "ext"
<character> ::= "char" | "utf8" | "utf16" | "utf32"
<string> ::= "string"
